export const COMPOSITE_DATA_ENTITIES_FETCH = 'COMPOSITE_DATA_ENTITIES_FETCH'
export const COMPOSITE_DATA_ENTITIES_FETCH_SUCCESS = 'COMPOSITE_DATA_ENTITIES_FETCH_SUCCESS'
export const COMPOSITE_DATA_ENTITIES_FETCH_ERROR = 'COMPOSITE_DATA_ENTITIES_FETCH_ERROR'

export const SESSION_END = 'SESSION_END'
export const SESSION_END_ERROR = 'SESSION_END_ERROR'
export const SESSION_END_SUCCESS = 'SESSION_END_SUCCESS'
export const SESSION_START = 'SESSION_START'
export const SESSION_START_ERROR = 'SESSION_START_ERROR'
export const SESSION_START_SUCCESS = 'SESSION_START_SUCCESS'

export const TWEET_POST = 'TWEET_POST' //right now only used for setting up a global error
export const TWEET_TOGGLE_LIKE = 'TWEET_TOGGLE_LIKE'

export const TWEETS_FETCH = 'TWEETS_FETCH'
export const TWEETS_FETCH_ERROR = 'TWEETS_FETCH_ERROR'
export const TWEETS_FETCH_SUCCESS = 'TWEETS_FETCH_SUCCESS'
export const TWEETS_REMOVE_ALL = 'TWEETS_REMOVE_ALL'

export const USER_TOGGLE_FOLLOW = 'USER_TOGGLE_FOLLOW'

export const USERS_FETCH = 'USERS_FETCH'
export const USERS_FETCH_ERROR = 'USERS_FETCH_ERROR'
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS'
export const USERS_REMOVE_ALL = 'USERS_REMOVE_ALL'



