export const COMPOSITE_DATA_CLEAR = 'COMPOSITE_DATA_CLEAR'
export const COMPOSITE_DATA_ENTITIES_FETCH = 'COMPOSITE_DATA_ENTITIES_FETCH'
export const COMPOSITE_DATA_ENTITIES_FETCH_SUCCESS = 'COMPOSITE_DATA_ENTITIES_FETCH_SUCCESS'
export const COMPOSITE_DATA_ENTITIES_FETCH_ERROR = 'COMPOSITE_DATA_ENTITIES_FETCH_ERROR'
export const COMPOSITE_DATA_SET_FETCH_STATUS = 'COMPOSITE_DATA_SET_FETCH_STATUS'
export const COMPOSITE_DATA_ENTITIES_UPDATE_FETCH_ERROR = 'COMPOSITE_DATA_ENTITIES_UPDATE_FETCH_ERROR'
export const COMPOSITE_DATA_ENTITIES_UPDATE_FETCH_SUCCESS = 'COMPOSITE_DATA_ENTITIES_UPDATE_FETCH_SUCCESS'

export const GLOBAL_ERROR_ADD = 'GLOBAL_ERROR_ADD'
export const GLOBAL_ERROR_REMOVE = 'GLOBAL_ERROR_REMOVE'

export const USERS_FETCH_STATUS_SET = 'FETCH_STATUS_SET'

export const NEW_LIKE_ADD_TO_USER_LIKES = 'NEW_LIKE_ADD_TO_USER_LIKES'
export const NEW_LIKE_REMOVE_FROM_USER_LIKES = 'NEW_LIKE_REMOVE_FROM_USER_LIKES'
export const NEW_TWEET_ADD_TO_FEED = 'NEW_TWEET_ADD_TO_FEED'
export const NEW_TWEET_ADD_TO_REPLIES = 'NEW_TWEET_ADD_TO_REPLIES'
export const NEW_TWEET_ADD_TO_USER_IMAGES = 'NEW_TWEET_ADD_TO_USER_IMAGES'
export const NEW_TWEET_ADD_TO_USER_TWEETS = 'NEW_TWEET_ADD_TO_USER_TWEETS'

export const PROFILE_UPDATE = 'PROFILE_UPDATE'

export const SESSION_END = 'SESSION_END'
export const SESSION_END_ERROR = 'SESSION_END_ERROR'
export const SESSION_END_SUCCESS = 'SESSION_END_SUCCESS'
export const SESSION_START = 'SESSION_START'
export const SESSION_START_ERROR = 'SESSION_START_ERROR'
export const SESSION_START_SUCCESS = 'SESSION_START_SUCCESS'

export const SOCKET_SET = 'SOCKET_SET'

export const TWEET_DELETE = 'TWEET_DELETE'
export const TWEET_POST = 'TWEET_POST' //right now only used for setting up a global error
export const TWEET_TOGGLE_LIKE = 'TWEET_TOGGLE_LIKE'
export const TWEET_UPDATE = 'TWEET_UPDATE'

export const TWEETS_FETCH = 'TWEETS_FETCH'
export const TWEETS_FETCH_ERROR = 'TWEETS_FETCH_ERROR'
export const TWEETS_FETCH_SUCCESS = 'TWEETS_FETCH_SUCCESS'
export const TWEETS_REMOVE_ALL = 'TWEETS_REMOVE_ALL'

export const USER_TOGGLE_FOLLOW = 'USER_TOGGLE_FOLLOW'
export const USER_UPDATE = 'USER_UPDATE'

export const USERS_FETCH = 'USERS_FETCH'
export const USERS_FETCH_ERROR = 'USERS_FETCH_ERROR'
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS'
export const USERS_REMOVE_ALL = 'USERS_REMOVE_ALL'


