export const LOADING = 'loading'
export const LOADED = 'loaded'
export const ERROR = 'error'
export const UPDATING = 'updating'
export const UPDATED = 'updated'
export const NOT_FOUND = 'not found'
export const PENDING_UPDATE = 'pending update'
export const SIGN_UP = 'sign up'
export const AUTHENTICATION_FAILED = 'authentication failed'
export const PASSWORD_RESET_LINK_SENT = 'password reset link sent'
export const PASSWORD_RESET = 'password reset'

export const URL = 'http://localhost/api'
export const URL_MAIN = 'http://localhost'
// export const URL = 'https://twitter-frontend-4zauvs5bna-uc.a.run.app/api'
// export const URL_MAIN = 'https://twitter-frontend-4zauvs5bna-uc.a.run.app'

export const defaultBackgroundColor = '#97bad1'